name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: python:3.10  # Imatge Docker de Python

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint pytest pytest-cov

    - name: Run pylint (analitzador de codi estàtic)
      run: |
        pylint $(git ls-files '*.py')

    - name: Run tests with coverage
      run: |
        pytest --cov=. --cov-report=term-missing

    - name: Upload coverage report (opcional)
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: .coverage
